### ISSUE TITLE
Online server to validate comments?

### ISSUE THREAD

**Issue by rgwilton** [mnot/ietf-comments#13]
Not an issue on the actual format, but related:

If we want folks to use this more widely then having an online server that validates the format (either as a file upload or a cut and paste) would likely be helpful rather than requiring everyone to install locally.

**Comment by mnot** [comment]
If it gets traction, definitely. Ideally it'd run in-browser.

**Comment by mnot** [comment]
I had a quick look at running it in [pyodide](https://pyodide.org/en/stable/) using [Pyscript](https://pyscript.net/). It seems possible, but would require some refactoring so we don't pull in libraries like requests for validation.

**Comment by mnot** [comment]
OK, I've got a page up at:
  https://mnot.github.io/ietf-comments/

It's pretty barebones but functional; I'll likely add to it and adjust over the next few days. Feedback much appreciated. 

Also, pyscript and pyodide are very early software, but it works in the browsers I've tested.
