### ISSUE TITLE
Pip install confused me

### ISSUE THREAD

**Issue by rgwilton** [mnot/ietf-comments#14]
1. The headline of the ietf-comments tool @ https://pypi.org/project/ietf-comments/ lists the install as "pip install ietf-comments" ... which failed.  Can the headline be changed to "pip3 install ietf-comments".

2. Even after the install (which didn't have any errors as far as I can see), I can't just run ietf-comments since it isn't on my path (even though python3 is).  Perhaps some further install/setup is required?  This is on ubuntu.

**Comment by rgwilton** [comment]
After a bit of hunting, it looks like ~/.local/bin needs to be added to my path.

**Comment by mnot** [comment]
Unfortunately, this is system-dependent; different OSs have different conventions, and package Python in their own unique ways.

I don't see any easy way of pulling this information out of Python; will continue to look. Hopefully, we'll get an online tool up for folks to validate with, so the number of people who have to install is relatively small.
