### ISSUE TITLE
Lars' Mega-Issue

### ISSUE THREAD

**Issue by larseggert** [mnot/ietf-comments#7]
With the review files I linked to https://github.com/larseggert/ietf-reviewtool/pull/10#issuecomment-1106118678, I get the following error when trying to validate them:
```
Traceback (most recent call last):
  File "/usr/local/bin/ietf-comments", line 71, in <module>
    comments = parse_comments(comment_file, cli)
  File "/usr/local/lib/python3.9/site-packages/ietf_comments/parser.py", line 160, in parse_comments
    renderer.render(doc)
  File "/usr/local/lib/python3.9/site-packages/commonmark/render/renderer.py", line 19, in render
    getattr(self, type_)(event['node'], event['entering'])
  File "/usr/local/lib/python3.9/site-packages/ietf_comments/parser.py", line 35, in heading
    getattr(self, f"handle_h{node.level}")(content)
AttributeError: 'CommentRenderer' object has no attribute 'handle_h4'
```

**Comment by mnot** [comment]
Ah, you're using headings inside of reviews? Will fix.

**Comment by mnot** [comment]
So, you're using level-4 headings under 'typos' and 'grammar/style' to indicate individual nits, even though we're already under a level-3 'nits' heading.

I think the right thing to do here is to give each one its own level-3 heading and forgo the current groupings; e.g.,

~~~ markdown
### Grammar/style: Paragraph 3
...
~~~

**Comment by larseggert** [comment]
I assumed the `h3` would create the (one) issue, and the `h4`s were just to make that issue test more readable. I don't think we need one issue per grammar nit?

**Comment by mnot** [comment]
Ah - if that's the case, I'll pass them through. I'm tempted to upgrade them to something like an h2 in the issue markup...

**Comment by mnot** [comment]
ok try now.

**Comment by larseggert** [comment]
That error is gone with 0.1.7, but I see some other issues:
* you convert all `h2` to lowercase
* text in `` (backticks) and `````` (code blocks) is missing from the output

**Comment by mnot** [comment]
OK, try 0.1.8.

**Comment by larseggert** [comment]
Better!

Next issue is that the tool doesn't seem to turn off colorization when the output is going somewhere other than the shell?

**Comment by mnot** [comment]
Try 0.1.9.
